"use client";
import { FormEvent, useEffect, useState } from "react";
import { Activity, CreditCard, Globe2, KeyRound, Network, Plus, Server, Settings, ShieldCheck, Users as UsersIcon } from "lucide-react";

type Plan = { id: string; name: string; price: number; tunnels: number; trafficGb: number; enabled: boolean };
type Node = { id: string; name: string; region: string; capabilities: string[]; status: string; lastSeen?: string };
type Tunnel = { id: string; name: string; localAddr: string; remotePort: number; status: string; nodeId?: string };
type AdminUser = { id: string; email: string; name: string; createdAt: string };
type Order = { id: string; userId: string; planId: string; amount: number; status: string; createdAt: string };

export default function AdminConsole() {
  const [page, setPage] = useState("overview");
  const [token, setToken] = useState("");
  const [plans, setPlans] = useState<Plan[]>([]); const [nodes, setNodes] = useState<Node[]>([]); const [tunnels, setTunnels] = useState<Tunnel[]>([]); const [users, setUsers] = useState<AdminUser[]>([]); const [orders, setOrders] = useState<Order[]>([]);
  const [message, setMessage] = useState("");
  useEffect(() => { void fetch("/api/v1/auth/admin/me", { credentials: "include" }).then((r) => { if (r.ok) setToken("cookie"); else setPage("access"); }); }, []);
  useEffect(() => { if (token) void refresh(); }, [token]);
  async function refresh() { const headers: HeadersInit = token === "cookie" ? {} : { Authorization: `Bearer ${token}` }; const options: RequestInit = { headers, credentials: "include" }; const [p, n, t, u, o] = await Promise.all([fetch("/api/v1/plans?all=true", options), fetch("/api/v1/nodes", options), fetch("/api/v1/tunnels", options), fetch("/api/v1/admin/users", options), fetch("/api/v1/admin/orders", options)]); if (p.ok) setPlans((await p.json()).data || []); if (n.ok) setNodes((await n.json()).data || []); if (t.ok) setTunnels((await t.json()).data || []); if (u.ok) setUsers((await u.json()).data || []); if (o.ok) setOrders((await o.json()).data || []); }
  async function createTunnel(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); const res = await fetch("/api/v1/tunnels", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ ...data, remotePort: Number(data.remotePort) }) }); setMessage(res.ok ? "隧道配置已创建，节点将在下一次轮询时接收命令。" : "创建失败，请检查管理员 token 和表单。"); e.currentTarget.reset(); void refresh(); }
  return <div className="shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">IN</span>infNet control</div><div className="nav-label">Workspace</div><nav className="nav"><Nav active={page === "overview"} onClick={() => setPage("overview")} icon={<Activity size={15} />} text="总览" /><Nav active={page === "services"} onClick={() => setPage("services")} icon={<Globe2 size={15} />} text="服务与线路" /><Nav active={page === "nodes"} onClick={() => setPage("nodes")} icon={<Server size={15} />} text="边缘节点" /><Nav active={page === "plans"} onClick={() => setPage("plans")} icon={<CreditCard size={15} />} text="套餐与计费" /></nav><div className="nav-label manage-label">Manage</div><Nav active={false} onClick={() => setPage("access")} icon={<KeyRound size={15} />} text="访问凭证" /><Nav active={false} onClick={() => setPage("users")} icon={<UsersIcon size={15} />} text="用户与订单" /><div className="side-bottom"><span className="status-dot" />控制面运行正常<br /><span className="mono">API / v1 · local state</span></div></aside><main className="main"><div className="topbar"><span className="crumb">INFNET / {page}</span><div className="top-actions"><span className="secure"><ShieldCheck size={14} />管理员控制台</span><div className="avatar">AD</div></div></div>{page === "overview" && <Overview plans={plans} nodes={nodes} tunnels={tunnels} setPage={setPage} />}{page === "plans" && <Plans plans={plans} token={token} refresh={refresh} />}{page === "nodes" && <Nodes nodes={nodes} token={token} refresh={refresh} />}{page === "services" && <Services tunnels={tunnels} nodes={nodes} onSubmit={createTunnel} message={message} />}{page === "access" && <Access token={token} setToken={setToken} />}{page === "users" && <Users users={users} orders={orders} />}</main></div>;
}
function Nav({ active, onClick, icon, text }: { active: boolean; onClick: () => void; icon: React.ReactNode; text: string }) { return <button className={active ? "active" : ""} onClick={onClick}>{icon}<span>{text}</span></button>; }
function Overview({ plans, nodes, tunnels, setPage }: { plans: Plan[]; nodes: Node[]; tunnels: Tunnel[]; setPage: (p: string) => void }) { return <><Header eyebrow="Operations overview" title="基础设施，一目了然。" text="监控边缘节点、线路和资源状态。" action="添加边缘节点" onAction={() => setPage("nodes")} /><div className="metrics"><Metric label="活跃节点" value={String(nodes.filter(n => n.status === "online").length)} /><Metric label="在线隧道" value={String(tunnels.length)} /><Metric label="公开套餐" value={String(plans.length)} /><Metric label="控制面" value="正常" /></div><div className="content-grid"><section className="panel"><div className="panel-head"><h2>节点健康度</h2><span>注册节点 {nodes.length}</span></div>{nodes.length ? <table className="table"><thead><tr><th>节点</th><th>区域</th><th>状态</th></tr></thead><tbody>{nodes.map(n => <tr key={n.id}><td><b>{n.name}</b><span className="sub">{n.id}</span></td><td>{n.region}</td><td><span className={n.status === "online" ? "pill" : "pill orange"}>{n.status}</span></td></tr>)}</tbody></table> : <Empty title="尚未接入节点" text="在服务器上运行 edge-agent 并使用节点 token 注册。" />}</section><section className="panel"><div className="panel-head"><h2>快速操作</h2><span>管理员</span></div><div className="quick"><button onClick={() => setPage("services")}><Network size={15} /><span>创建隧道</span></button><button onClick={() => setPage("plans")}><CreditCard size={15} /><span>管理套餐</span></button><button onClick={() => setPage("access")}><Settings size={15} /><span>配置凭证</span></button></div></section></div></>; }
function Header({ eyebrow, title, text, action, onAction }: { eyebrow: string; title: string; text: string; action?: string; onAction?: () => void }) { return <div className="heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{text}</p></div>{action && <button className="primary" onClick={onAction}><Plus size={14} />{action}</button>}</div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><div className="label">{label}</div><strong>{value}</strong><span className="trend">实时数据</span></div>; }
function Plans({ plans, token, refresh }: { plans: Plan[]; token: string; refresh: () => Promise<void> }) { async function create(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const body = Object.fromEntries(new FormData(e.currentTarget)); const res = await fetch("/api/v1/plans", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ ...body, price: Number(body.price), tunnels: Number(body.tunnels), trafficGb: Number(body.trafficGb) }) }); if (res.ok) { e.currentTarget.reset(); void refresh(); } } async function toggle(plan: Plan) { const res = await fetch(`/api/v1/plans/${plan.id}`, { method: plan.enabled ? "DELETE" : "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: plan.enabled ? undefined : JSON.stringify({ enabled: true }) }); if (res.ok) void refresh(); } return <><Header eyebrow="Commerce" title="套餐与计费" text="管理用户可购买的资源配额。" /><section className="panel"><h2>新建套餐</h2><form onSubmit={(e) => void create(e)} className="form"><input name="name" placeholder="套餐名称" required /><input name="price" type="number" min={0} placeholder="月价（元）" required /><input name="tunnels" type="number" placeholder="隧道数，-1 为不限" required /><input name="trafficGb" type="number" min={1} placeholder="流量 GB" required /><button className="primary" type="submit">保存套餐</button></form></section><div className="cards">{plans.map(p => <div className="plan-card" key={p.id}><div className="eyebrow">Public plan</div><h3>{p.name}</h3><div className="price">¥{p.price} <small>/ 月</small></div><div className="features"><div>隧道：{p.tunnels < 0 ? "不限" : p.tunnels}</div><div>流量：{p.trafficGb} GB / 月</div><div>状态：{p.enabled ? "公开" : "停用"}</div></div><button className="small-btn" onClick={() => void toggle(p)}>{p.enabled ? "停用套餐" : "重新启用"}</button></div>)}</div></>; }
function Nodes({ nodes, token, refresh }: { nodes: Node[]; token: string; refresh: () => Promise<void> }) { async function create(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const body = Object.fromEntries(new FormData(e.currentTarget)); const res = await fetch("/api/v1/nodes", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ ...body, capabilities: ["cdn", "frp"] }) }); if (res.ok) { const result = await res.json(); alert(`节点 token（仅显示一次）：${result.token}`); e.currentTarget.reset(); void refresh(); } } async function rotate(id: string) { const res = await fetch(`/api/v1/nodes/${id}/token`, { method: "POST", headers: { Authorization: `Bearer ${token}` } }); if (res.ok) { const result = await res.json(); alert(`新节点 token（旧 token 已失效）：${result.token}`); } } return <><Header eyebrow="Infrastructure" title="边缘节点" text="接入并监控 CDN 与 FRP 服务器。" /><section className="panel"><h2>预配节点</h2><form onSubmit={(e) => void create(e)} className="form"><input name="name" placeholder="节点名称" required /><input name="region" placeholder="区域，例如 cn-shanghai" required /><button className="primary" type="submit">生成节点 token</button></form></section><section className="panel"><div className="panel-head"><h2>已注册节点</h2><button className="small-btn" onClick={() => void refresh()}>刷新</button></div><table className="table"><thead><tr><th>名称</th><th>区域</th><th>能力</th><th>状态</th><th>最近心跳</th><th>操作</th></tr></thead><tbody>{nodes.map(n => <tr key={n.id}><td><b>{n.name}</b><span className="sub mono">{n.id}</span></td><td>{n.region}</td><td>{n.capabilities.join(" + ")}</td><td><span className={n.status === "online" ? "pill" : "pill orange"}>{n.status}</span></td><td className="mono">{n.lastSeen ? new Date(n.lastSeen).toLocaleString() : "-"}</td><td><button className="small-btn" onClick={() => void rotate(n.id)}>轮换 token</button></td></tr>)}</tbody></table>{!token && <p className="notice">请先在“访问凭证”中配置管理员 token。</p>}</section></>; }
function Services({ tunnels, nodes, onSubmit, message }: { tunnels: Tunnel[]; nodes: Node[]; onSubmit: (e: FormEvent<HTMLFormElement>) => void; message: string }) { return <><Header eyebrow="Traffic control" title="服务与线路" text="配置并发布自有 FRP 隧道。" /><section className="panel"><h2>创建隧道</h2><form onSubmit={onSubmit} className="form"><input name="name" placeholder="服务名称" required /><input name="localAddr" placeholder="127.0.0.1:8080" required /><input name="remotePort" type="number" min="1024" max="65535" placeholder="远端端口" required /><select name="nodeId" defaultValue=""><option value="">稍后分配节点</option>{nodes.map(n => <option key={n.id} value={n.id}>{n.name}</option>)}</select><button className="primary" type="submit">创建配置</button></form>{message && <p className="notice">{message}</p>}</section><section className="panel"><div className="panel-head"><h2>已创建隧道</h2><span>{tunnels.length} 条</span></div><table className="table"><thead><tr><th>名称</th><th>本地服务</th><th>远端端口</th><th>状态</th></tr></thead><tbody>{tunnels.map(t => <tr key={t.id}><td><b>{t.name}</b></td><td className="mono">{t.localAddr}</td><td className="mono">{t.remotePort}</td><td><span className="pill">{t.status}</span></td></tr>)}</tbody></table></section></>; }
function Access({ setToken }: { token: string; setToken: (v: string) => void }) { const [value, setValue] = useState(""); async function login() { const response = await fetch("/api/v1/auth/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ token: value }) }); if (response.ok) { setToken(value); setValue(""); } } return <><Header eyebrow="Security" title="管理员登录" text="凭证只用于建立 HttpOnly 管理员 session。" /><section className="panel narrow"><label className="field-label">ADMIN TOKEN</label><input value={value} onChange={e => setValue(e.target.value)} type="password" placeholder="输入服务端配置的 token" /><button className="primary" onClick={() => void login()}>登录控制台</button><p className="notice">生产环境仍应配置多管理员 RBAC、审计日志和短期 session。</p></section></>; }
function Users({ users, orders }: { users: AdminUser[]; orders: Order[] }) { return <><Header eyebrow="Operations" title="用户与订单" text="查看账户、套餐购买和支付状态。" /><section className="panel"><div className="panel-head"><h2>注册用户</h2><span>{users.length} 个</span></div><table className="table"><thead><tr><th>用户</th><th>邮箱</th><th>注册时间</th></tr></thead><tbody>{users.map(user => <tr key={user.id}><td><b>{user.name || "未命名"}</b><span className="sub mono">{user.id}</span></td><td>{user.email}</td><td className="mono">{new Date(user.createdAt).toLocaleString()}</td></tr>)}</tbody></table>{!users.length && <Empty title="暂无用户" text="用户注册后会出现在这里。" />}</section><section className="panel"><div className="panel-head"><h2>最近订单</h2><span>{orders.length} 条</span></div><table className="table"><thead><tr><th>订单</th><th>用户</th><th>套餐</th><th>金额</th><th>状态</th></tr></thead><tbody>{orders.map(order => <tr key={order.id}><td className="mono">{order.id}</td><td className="mono">{order.userId}</td><td>{order.planId}</td><td>¥{order.amount}</td><td><span className={order.status === "paid" ? "pill" : "pill orange"}>{order.status}</span></td></tr>)}</tbody></table>{!orders.length && <Empty title="暂无订单" text="用户提交订单后会出现在这里。" />}</section></>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty"><b>{title}</b><span>{text}</span></div>; }
