"use client";

import { FormEvent, useEffect, useState } from "react";
import { ArrowRight, Check, ChevronDown, Cloud, Copy, ExternalLink, Globe2, LockKeyhole, LogOut, Menu, Network, Server, ShieldCheck, Sparkles, X, Zap } from "lucide-react";

type View = "site" | "auth" | "dashboard";
type Plan = { id: string; name: string; price: number; tunnels: number; trafficGb: number; enabled?: boolean };
type Order = { id: string; planId: string; amount: number; status: string };
type Tunnel = { id: string; name: string; localAddr: string; remotePort: number; ticket: string; status: string };
type CdnRoute = { id: string; hostname: string; origin: string; cacheSeconds: number; status: string };
type Usage = { planId: string; bytes: number; trafficGb: number; overQuota: boolean };

const fallbackPlans: Plan[] = [
  { id: "starter", name: "Starter", price: 19, tunnels: 3, trafficGb: 100 },
  { id: "growth", name: "Growth", price: 69, tunnels: 15, trafficGb: 1024 },
  { id: "scale", name: "Scale", price: 199, tunnels: -1, trafficGb: 5120 },
];

export default function CustomerPortal({ initialView = "site" }: { initialView?: View }) {
  const [view, setView] = useState<View>(initialView);
  const [plans, setPlans] = useState<Plan[]>(fallbackPlans);
  const [selectedPlan, setSelectedPlan] = useState("");
  const [menuOpen, setMenuOpen] = useState(false);
  const [token, setToken] = useState("");
  const [error, setError] = useState("");
  const [orders, setOrders] = useState<Order[]>([]);
  const [tunnels, setTunnels] = useState<Tunnel[]>([]);
  const [cdnRoutes, setCdnRoutes] = useState<CdnRoute[]>([]);
  const [usage, setUsage] = useState<Usage[]>([]);

  useEffect(() => { void fetch("/api/v1/plans").then((r) => r.json()).then((body) => { if (body.data?.length) setPlans(body.data); }); void fetch("/api/v1/auth/me", { credentials: "include" }).then((r) => { if (r.ok) { setToken("cookie"); if (initialView === "auth") setView("dashboard"); } }); }, [initialView]);
  useEffect(() => { if (token) void refresh(); }, [token]);

  async function refresh() {
    const options: RequestInit = { credentials: "include" };
    const [ordersRes, tunnelsRes, cdnRes, usageRes] = await Promise.all([fetch("/api/v1/orders", options), fetch("/api/v1/my/tunnels", options), fetch("/api/v1/my/cdn", options), fetch("/api/v1/my/usage", options)]);
    if (ordersRes.ok) setOrders((await ordersRes.json()).data || []);
    if (tunnelsRes.ok) setTunnels((await tunnelsRes.json()).data || []);
    if (cdnRes.ok) setCdnRoutes((await cdnRes.json()).data || []);
    if (usageRes.ok) setUsage((await usageRes.json()).data || []);
  }
  function choosePlan(id: string) { setSelectedPlan(id); setView(token ? "dashboard" : "auth"); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function auth(e: FormEvent<HTMLFormElement>, action: "register" | "login") { e.preventDefault(); setError(""); const res = await fetch(`/api/v1/auth/${action}`, { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify(Object.fromEntries(new FormData(e.currentTarget))) }); const body = await res.json(); if (!res.ok) { setError(body.error || "操作失败，请稍后重试"); return; } setToken("cookie"); setView("dashboard"); }
  async function buy(planId: string) { if (!token) { setSelectedPlan(planId); setView("auth"); return; } const res = await fetch("/api/v1/orders", { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ planId }) }); const body = await res.json(); if (!res.ok) setError(body.error || "下单失败"); else if (body.checkout?.url) window.location.assign(body.checkout.url); else void refresh(); }
  async function logout() { await fetch("/api/v1/auth/logout", { method: "POST", credentials: "include" }); setToken(""); setView("site"); }

  return <div className="site-shell">
    <header className="site-nav"><a className="site-brand" href="/"><span className="brand-mark">IN</span><span>infNet</span></a><nav className={menuOpen ? "site-links open" : "site-links"}><a href="/" onClick={() => setMenuOpen(false)}>首页</a><a href="/platform" onClick={() => setMenuOpen(false)}>边缘加速</a><a href="/tunnel" onClick={() => setMenuOpen(false)}>内网穿透</a><a href="/pricing" onClick={() => setMenuOpen(false)}>价格</a><a className="external-link" href="https://monitor.infvar.com" target="_blank" rel="noreferrer" onClick={() => setMenuOpen(false)}>节点状态 <ExternalLink size={13} /></a></nav><div className="site-nav-actions"><a className="text-link desktop-only" href={token ? "/dashboard" : "/login"}>登录</a><button className="nav-cta desktop-only" onClick={() => setView(token ? "dashboard" : "auth")}>{token ? "进入控制台" : "开始使用"}<ArrowRight size={15} /></button><button className="menu-toggle" aria-label="打开导航" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div></header>
    {view === "site" && <SalesPage plans={plans} onChoose={choosePlan} />}
    {view === "auth" && <AuthView selectedPlan={selectedPlan} error={error} onAuth={auth} onBack={() => setView("site")} />}
    {view === "dashboard" && <Dashboard plans={plans} selectedPlan={selectedPlan} orders={orders} tunnels={tunnels} cdnRoutes={cdnRoutes} usage={usage} error={error} setError={setError} onBuy={buy} onRefresh={refresh} onLogout={logout} />}
  </div>;
}

function SalesPage({ plans, onChoose }: { plans: Plan[]; onChoose: (id: string) => void }) {
  return <>
    <main>
      <section className="hero"><div className="hero-copy"><div className="eyebrow-light"><span className="live-dot" />全域边缘网络 · 现在可用</div><h1>让每一次访问，<em>更快、更稳。</em></h1><p>用一套简单的控制台，使用 infNet 提供的节点完成 CDN 加速与私有 FRP 内网穿透。你只需配置自己的域名、源站或内网服务，几分钟即可上线。</p><div className="hero-actions"><a className="button button-bright" href="/pricing">查看套餐 <ArrowRight size={17} /></a><a className="hero-secondary" href="#platform">了解平台 <span>↓</span></a></div><div className="hero-proof"><span><ShieldCheck size={15} /> TLS 1.3 加密</span><span><Zap size={15} /> 平台边缘节点</span><span><LockKeyhole size={15} /> 按量可控</span></div></div><div className="hero-visual"><div className="visual-glow" /><div className="network-card"><div className="network-card-top"><span className="tiny-label">NETWORK STATUS</span><span className="online"><i /> OPERATIONAL</span></div><div className="network-map"><div className="map-line line-one" /><div className="map-line line-two" /><div className="map-line line-three" /><span className="map-node node-a"><i /></span><span className="map-node node-b"><i /></span><span className="map-node node-c"><i /></span><span className="map-node node-d"><i /></span><span className="map-core"><b>IN</b></span></div><div className="network-card-bottom"><div><strong>42 ms</strong><span>平均响应</span></div><div><strong>99.99%</strong><span>可用性</span></div><div><strong>24/7</strong><span>自动守护</span></div></div></div></div></section>
      <section className="service-boundary"><span className="eyebrow">平台提供节点，用户专注业务</span><strong>CDN 加速和 FRP 内网穿透，使用同一批 infNet 边缘节点。</strong><span>你不需要自建 CDN 网络或公网中转节点，只需在控制台配置自己的域名、源站和内网服务。</span></section>
      <section className="trust-strip"><span>为开发者和成长中的团队打造</span><div><b>ACME</b><b>northstar</b><b>orbit</b><b>stackly</b><b>vertex</b></div></section>
      <section className="section section-light" id="platform"><div className="section-intro"><div className="eyebrow">平台能力</div><h2>你的业务，值得一张<br /><span>更聪明的网络。</span></h2><p>infNet 把复杂的边缘基础设施变成清晰、可控的产品体验。</p></div><div className="feature-grid"><Feature icon={<Globe2 />} number="01" title="CDN 加速" text="静态与动态内容就近分发，内置缓存策略与源站保护，让页面在用户身边打开。" /><Feature icon={<Network />} number="02" title="私有 FRP 隧道" text="把本地服务安全发布到公网。自研客户端与 TLS 1.3 协议，连接稳定且完全可控。" /><Feature icon={<Server />} number="03" title="节点自由扩展" text="在自己的服务器运行 edge-agent，自动接入平台，按区域构建属于你的边缘网络。" /><Feature icon={<Cloud />} number="04" title="用量透明" text="流量、线路和套餐配额实时可见。没有隐藏费用，业务增长时再平滑升级。" /></div></section>
      <section className="section dark-section" id="how"><div className="section-intro inverse"><div className="eyebrow-light">三步上线</div><h2>从注册到上线，<br /><em>不超过十分钟。</em></h2></div><div className="steps"><Step n="01" title="选择适合你的套餐" text="按隧道数量与月流量选择，随时可以升级。" /><Step n="02" title="接入你的边缘节点" text="运行一条命令，服务器会自动注册并同步配置。" /><Step n="03" title="发布你的服务" text="配置域名或端口，复制客户端命令，立即开始转发。" /></div></section>
      <section className="faq-section" id="faq"><div className="section-intro"><div className="eyebrow">常见问题</div><h2>还有疑问？<br /><span>这里有答案。</span></h2></div><div className="faq-list"><Faq q="我需要自己准备服务器吗？" a="CDN 与 FRP 节点需要运行在你的服务器上。你可以使用云服务器或物理机，我们提供自动注册的 edge-agent。" /><Faq q="可以随时更换套餐吗？" a="可以。升级立即生效，套餐额度与订单状态都可以在客户控制台查看。" /><Faq q="客户端是开源 FRP 吗？" a="不是。infNet 使用自研客户端与私有协议，客户端只负责安全连接与端口转发。" /></div></section>
    </main><footer className="site-footer"><div className="site-brand"><span className="brand-mark">IN</span><span>infNet</span></div><span>边缘网络，简单可控。</span><div><a href="/login">登录</a><a href="/admin">管理员入口</a></div></footer>
  </>;
}

function Feature({ icon, number, title, text }: { icon: React.ReactNode; number: string; title: string; text: string }) { const safeTitle = title === "节点自由扩展" ? "平台节点承载" : title; const safeText = title === "节点自由扩展" ? "CDN 与 FRP 使用 infNet 提供的边缘节点，节点运营、线路和可用性由平台负责。" : text; return <article className="feature"><div className="feature-top"><span className="feature-icon">{icon}</span><span>{number}</span></div><h3>{safeTitle}</h3><p>{safeText}</p><a href="/pricing">了解套餐 <ArrowRight size={14} /></a></article>; }
function Step({ n, title, text }: { n: string; title: string; text: string }) { const safeTitle = n === "02" ? "平台分配服务资源" : title; const safeText = n === "02" ? "选择服务后，平台自动准备可用的 CDN 线路或 FRP 中转资源，无需自建节点。" : text; return <article className="step"><span>{n}</span><div><h3>{safeTitle}</h3><p>{safeText}</p></div></article>; }
function PlanCard({ plan, featured, onChoose }: { plan: Plan; featured: boolean; onChoose: (id: string) => void }) { return <article className={featured ? "price-card featured" : "price-card"}>{featured && <div className="popular">最受欢迎</div>}<div className="price-card-head"><span>{plan.name}</span>{featured ? <Sparkles size={17} /> : <span className="price-mark">○</span>}</div><p className="price-card-desc">{plan.id === "starter" ? "个人项目与小型服务" : plan.id === "growth" ? "成长中的团队与产品" : "高流量业务与多节点"}</p><div className="price-value"><b>¥{plan.price}</b><span>/ 月</span></div><div className="price-rule" /><ul><li><Check size={15} /> {plan.tunnels < 0 ? "不限" : plan.tunnels} 条 FRP 隧道</li><li><Check size={15} /> {plan.trafficGb >= 1024 ? `${plan.trafficGb / 1024} TB` : plan.trafficGb + " GB"} 月流量</li><li><Check size={15} /> CDN 缓存与 TLS 1.3</li><li><Check size={15} /> 节点自动同步</li></ul><button className={featured ? "button button-dark" : "button button-outline"} onClick={() => onChoose(plan.id)}>选择 {plan.name} <ArrowRight size={15} /></button></article>; }
function Faq({ q, a }: { q: string; a: string }) { const [open, setOpen] = useState(false); const safeAnswer = q.includes("服务器") ? "不需要。CDN 与 FRP 使用 infNet 提供和运营的边缘节点，你只需配置自己的域名、源站或内网服务。" : a; return <div className={open ? "faq open" : "faq"}><button onClick={() => setOpen(!open)}><span>{q}</span>{open ? <X size={17} /> : <ChevronDown size={17} />}</button>{open && <p>{safeAnswer}</p>}</div>; }

function AuthView({ selectedPlan, error, onAuth, onBack }: { selectedPlan: string; error: string; onAuth: (e: FormEvent<HTMLFormElement>, action: "register" | "login") => void; onBack: () => void }) { return <main className="auth-page"><div className="auth-back"><button onClick={onBack}>← 返回首页</button></div><div className="auth-layout"><div className="auth-pitch"><div className="eyebrow-light">开始使用 infNet</div><h1>把你的服务，<br /><em>带到更近的地方。</em></h1><p>创建账户后即可选择套餐、接入节点并管理所有 CDN 与 FRP 服务。</p><div className="auth-points"><span><Check size={15} /> 立即拥有客户控制台</span><span><Check size={15} /> 透明的流量与订单记录</span><span><Check size={15} /> 随时升级，不锁定长期合约</span></div></div><div className="auth-card"><div className="auth-tabs"><strong>创建账户</strong><span>已有账户？<button onClick={() => (document.querySelector(".auth-login") as HTMLElement)?.focus()}>直接登录</button></span></div><AuthForm action="register" onSubmit={onAuth} selectedPlan={selectedPlan} />{error && <p className="form-error">{error}</p>}<div className="auth-divider"><span>已有账户</span></div><div className="auth-login"><AuthForm action="login" onSubmit={onAuth} /></div></div></div></main>; }
function AuthForm({ action, onSubmit, selectedPlan }: { action: "register" | "login"; onSubmit: (e: FormEvent<HTMLFormElement>, action: "register" | "login") => void; selectedPlan?: string }) { return <form className="auth-form" onSubmit={(e) => { e.preventDefault(); onSubmit(e, action); }}>{action === "register" && <><label>姓名<input name="name" placeholder="你的姓名或团队名称" /></label><label>邮箱<input name="email" type="email" placeholder="you@company.com" required /></label></>}{action === "login" && <label>邮箱<input name="email" type="email" placeholder="you@company.com" required /></label>}<label>密码<input name="password" type="password" minLength={action === "register" ? 10 : undefined} placeholder={action === "register" ? "至少 10 位" : "输入密码"} required /></label>{selectedPlan && action === "register" && <input type="hidden" name="planId" value={selectedPlan} />}<button className="button button-dark" type="submit">{action === "register" ? "创建账户并继续" : "登录控制台"}<ArrowRight size={15} /></button></form>; }

function Dashboard({ plans, selectedPlan, orders, tunnels, cdnRoutes, usage, error, setError, onBuy, onRefresh, onLogout }: { plans: Plan[]; selectedPlan: string; orders: Order[]; tunnels: Tunnel[]; cdnRoutes: CdnRoute[]; usage: Usage[]; error: string; setError: (s: string) => void; onBuy: (id: string) => void; onRefresh: () => Promise<void>; onLogout: () => void }) {
  const [tab, setTab] = useState(selectedPlan ? "plans" : "overview");
  const [showTunnel, setShowTunnel] = useState(false);
  const [showCdn, setShowCdn] = useState(false);
  async function create(e: FormEvent<HTMLFormElement>, kind: "tunnel" | "cdn") { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); const endpoint = kind === "tunnel" ? "/api/v1/my/tunnels" : "/api/v1/my/cdn"; const payload = kind === "tunnel" ? { ...data, remotePort: Number(data.remotePort) } : { ...data, cacheSeconds: Number(data.cacheSeconds) }; const res = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify(payload) }); if (!res.ok) setError((await res.json()).error || "配置失败"); else { setError(""); e.currentTarget.reset(); void onRefresh(); kind === "tunnel" ? setShowTunnel(false) : setShowCdn(false); } }
  return <main className="dashboard"><aside className="dash-sidebar"><a className="site-brand" href="/"><span className="brand-mark">IN</span><span>infNet</span></a><div className="dash-label">Workspace</div><button className={tab === "overview" ? "dash-nav active" : "dash-nav"} onClick={() => setTab("overview")}><Sparkles size={16} /> 总览</button><button className={tab === "plans" ? "dash-nav active" : "dash-nav"} onClick={() => setTab("plans")}><Zap size={16} /> 套餐与购买</button><button className={tab === "tunnels" ? "dash-nav active" : "dash-nav"} onClick={() => setTab("tunnels")}><Network size={16} /> FRP 隧道</button><button className={tab === "cdn" ? "dash-nav active" : "dash-nav"} onClick={() => setTab("cdn")}><Globe2 size={16} /> CDN 路由</button><button className={tab === "orders" ? "dash-nav active" : "dash-nav"} onClick={() => setTab("orders")}><Copy size={16} /> 订单记录</button><div className="dash-bottom"><button className="dash-nav" onClick={onLogout}><LogOut size={16} /> 退出账户</button><span className="account-chip"><i /> 服务运行正常</span></div></aside><section className="dash-content"><div className="dash-top"><span className="mobile-brand"><span className="brand-mark">IN</span> infNet</span><span className="dash-breadcrumb">客户控制台 / {tab}</span><div><button className="icon-refresh" title="刷新" onClick={() => void onRefresh()}>↻</button><span className="user-avatar">ME</span></div></div>{error && <div className="dash-error">{error}<button onClick={() => setError("")}><X size={14} /></button></div>}{tab === "overview" && <Overview tunnels={tunnels} cdnRoutes={cdnRoutes} usage={usage} setTab={setTab} />}{tab === "plans" && <PlansPanel plans={plans} selectedPlan={selectedPlan} onBuy={onBuy} />}{tab === "tunnels" && <TunnelPanel tunnels={tunnels} show={showTunnel} setShow={setShowTunnel} onCreate={create} />}{tab === "cdn" && <CdnPanel routes={cdnRoutes} show={showCdn} setShow={setShowCdn} onCreate={create} />}{tab === "orders" && <OrdersPanel orders={orders} />}</section></main>;
}
function Overview({ tunnels, cdnRoutes, usage, setTab }: { tunnels: Tunnel[]; cdnRoutes: CdnRoute[]; usage: Usage[]; setTab: (tab: string) => void }) { const bytes = usage.reduce((sum, item) => sum + item.bytes, 0); return <><div className="dash-heading"><div><div className="eyebrow">Workspace overview</div><h1>欢迎回来。</h1><p>查看你的服务状态和本月网络用量。</p></div><button className="button button-dark" onClick={() => setTab("tunnels")}><Network size={15} /> 创建隧道</button></div><div className="dash-metrics"><div><span>活跃隧道</span><strong>{tunnels.filter((t) => t.status === "active").length}</strong><small>共 {tunnels.length} 条配置</small></div><div><span>CDN 路由</span><strong>{cdnRoutes.length}</strong><small>边缘分发线路</small></div><div><span>本月流量</span><strong>{(bytes / 1024 ** 3).toFixed(2)}<em> GB</em></strong><small>来自节点心跳上报</small></div><div><span>服务状态</span><strong className="status-good">正常</strong><small>全部系统运行中</small></div></div><div className="dash-columns"><section className="dash-panel"><div className="dash-panel-head"><div><h2>最近服务</h2><p>你的 CDN 与 FRP 配置</p></div><button onClick={() => setTab("tunnels")}>查看全部 <ArrowRight size={14} /></button></div>{!tunnels.length && !cdnRoutes.length ? <EmptyState text="还没有服务配置，选择一个套餐后开始。" action="查看套餐" onClick={() => setTab("plans")} /> : <div className="service-list">{tunnels.slice(0, 3).map((t) => <div className="service-row" key={t.id}><span className="service-symbol purple"><Network size={16} /></span><div><b>{t.name}</b><span>{t.localAddr} → :{t.remotePort}</span></div><Status value={t.status} /></div>)}{cdnRoutes.slice(0, 3).map((r) => <div className="service-row" key={r.id}><span className="service-symbol green"><Globe2 size={16} /></span><div><b>{r.hostname}</b><span>{r.origin}</span></div><Status value={r.status} /></div>)}</div>}</section><section className="dash-panel usage-panel"><div className="dash-panel-head"><div><h2>流量配额</h2><p>本月套餐使用情况</p></div><button onClick={() => setTab("plans")}>升级 <ArrowRight size={14} /></button></div>{usage.length ? usage.map((item) => <div className="usage-bar" key={item.planId}><div><b>{item.planId}</b><span>{(item.bytes / 1024 ** 3).toFixed(2)} / {item.trafficGb} GB</span></div><i><em style={{ width: `${Math.min(100, item.trafficGb ? (item.bytes / 1024 ** 3 / item.trafficGb) * 100 : 0)}%` }} /></i></div>) : <EmptyState text="产生流量后，这里会显示实时配额。" />}</section></div></>; }
function PlansPanel({ plans, selectedPlan, onBuy }: { plans: Plan[]; selectedPlan: string; onBuy: (id: string) => void }) { return <><div className="dash-heading"><div><div className="eyebrow">Plans & billing</div><h1>选择套餐</h1><p>为你的服务选择合适的资源额度。</p></div></div><div className="dash-plan-grid">{plans.map((p) => <PlanCard key={p.id} plan={p} featured={p.id === "growth" || p.id === selectedPlan} onChoose={onBuy} />)}</div></>; }
function TunnelPanel({ tunnels, show, setShow, onCreate }: { tunnels: Tunnel[]; show: boolean; setShow: (v: boolean) => void; onCreate: (e: FormEvent<HTMLFormElement>, kind: "tunnel" | "cdn") => void }) { return <><div className="dash-heading"><div><div className="eyebrow">FRP tunnels</div><h1>FRP 隧道</h1><p>将本地服务安全发布到公网。</p></div><button className="button button-dark" onClick={() => setShow(!show)}><Network size={15} /> 创建隧道</button></div>{show && <section className="dash-form"><h2>新建隧道</h2><form onSubmit={(e) => onCreate(e, "tunnel")}><input name="name" placeholder="服务名称" required /><input name="localAddr" placeholder="127.0.0.1:8080" required /><input name="remotePort" type="number" min={1024} max={65535} placeholder="远端端口" required /><select name="planId" defaultValue="starter"><option value="starter">Starter</option><option value="growth">Growth</option><option value="scale">Scale</option></select><button className="button button-dark" type="submit">创建配置</button></form></section>}<section className="dash-panel table-panel"><div className="dash-panel-head"><div><h2>我的隧道</h2><p>{tunnels.length} 条配置</p></div></div>{tunnels.length ? tunnels.map((t) => <div className="resource-row" key={t.id}><span className="service-symbol purple"><Network size={16} /></span><div><b>{t.name}</b><span>{t.localAddr} → :{t.remotePort}</span></div><Status value={t.status} /><button className="row-action" onClick={() => navigator.clipboard?.writeText(t.ticket)} title="复制 ticket"><Copy size={15} /></button></div>) : <EmptyState text="还没有隧道配置。" />}</section></>; }
function CdnPanel({ routes, show, setShow, onCreate }: { routes: CdnRoute[]; show: boolean; setShow: (v: boolean) => void; onCreate: (e: FormEvent<HTMLFormElement>, kind: "tunnel" | "cdn") => void }) { return <><div className="dash-heading"><div><div className="eyebrow">CDN delivery</div><h1>CDN 路由</h1><p>让内容从离用户最近的节点送达。</p></div><button className="button button-dark" onClick={() => setShow(!show)}><Globe2 size={15} /> 创建路由</button></div>{show && <section className="dash-form"><h2>新建 CDN 路由</h2><form onSubmit={(e) => onCreate(e, "cdn")}><input name="hostname" placeholder="cdn.example.com" required /><input name="origin" placeholder="https://origin.example.com" required /><input name="cacheSeconds" type="number" min={0} max={86400} defaultValue={60} /><select name="planId" defaultValue="starter"><option value="starter">Starter</option><option value="growth">Growth</option><option value="scale">Scale</option></select><button className="button button-dark" type="submit">发布路由</button></form></section>}<section className="dash-panel table-panel"><div className="dash-panel-head"><div><h2>我的 CDN</h2><p>{routes.length} 条分发线路</p></div></div>{routes.length ? routes.map((r) => <div className="resource-row" key={r.id}><span className="service-symbol green"><Globe2 size={16} /></span><div><b>{r.hostname}</b><span>{r.origin} · 缓存 {r.cacheSeconds}s</span></div><Status value={r.status} /></div>) : <EmptyState text="还没有 CDN 路由。" />}</section></>; }
function OrdersPanel({ orders }: { orders: Order[] }) { return <><div className="dash-heading"><div><div className="eyebrow">Billing history</div><h1>订单记录</h1><p>查看套餐订单与支付状态。</p></div></div><section className="dash-panel table-panel">{orders.length ? orders.map((o) => <div className="resource-row" key={o.id}><span className="order-mark">¥</span><div><b>{o.planId} 套餐</b><span>{o.id}</span></div><strong>¥{o.amount}</strong><Status value={o.status} /></div>) : <EmptyState text="暂无订单记录。" />}</section></>; }
function Status({ value }: { value: string }) { return <span className={value === "active" || value === "paid" ? "status-pill good" : "status-pill"}><i />{value === "active" ? "运行中" : value === "paid" ? "已支付" : value}</span>; }
function EmptyState({ text, action, onClick }: { text: string; action?: string; onClick?: () => void }) { return <div className="empty-state"><span>{text}</span>{action && <button onClick={onClick}>{action} <ArrowRight size={14} /></button>}</div>; }
