import { ArrowRight, Check, ChevronRight, ExternalLink, Globe2, LockKeyhole, Network, Radar, Server, ShieldCheck, Terminal, Zap } from "lucide-react";

type MarketingPage = "platform" | "tunnel" | "network" | "pricing" | "docs";

export function MarketingNav({ page }: { page: MarketingPage }) {
  return <header className="site-nav marketing-nav"><a className="site-brand" href="/"><span className="brand-mark">IN</span><span>infNet</span></a><nav className="site-links marketing-links"><a href="/">首页</a><a className={page === "platform" ? "active" : undefined} href="/platform">边缘加速</a><a className={page === "tunnel" ? "active" : undefined} href="/tunnel">内网穿透</a><a className={page === "pricing" ? "active" : undefined} href="/pricing">价格</a><a className="external-link" href="https://monitor.infvar.com" target="_blank" rel="noreferrer">节点状态 <ExternalLink size={13} /></a></nav><div className="site-nav-actions"><a className="text-link desktop-only" href="/login">登录</a><a className="nav-cta" href="/login">开始使用 <ArrowRight size={15} /></a></div></header>;
}

export function MarketingFooter() {
  return <footer className="site-footer marketing-footer"><div className="site-brand"><span className="brand-mark">IN</span><span>infNet</span></div><span>把复杂的边缘网络，变成清晰的产品。</span><div><a href="/platform">平台能力</a><a href="/docs">开发者文档</a><a href="/admin">管理员入口</a></div></footer>;
}

function PageFrame({ children, page }: { children: React.ReactNode; page: MarketingPage }) { return <div className="marketing-shell"><MarketingNav page={page} />{children}<MarketingFooter /></div>; }
function SignalTag({ children }: { children: React.ReactNode }) { return <div className="signal-tag"><i />{children}</div>; }

function AnimatedNetwork({ large = false }: { large?: boolean }) {
  return <div className={large ? "animated-network large" : "animated-network"} aria-label="边缘节点网络示意"><div className="network-ring ring-one" /><div className="network-ring ring-two" /><div className="network-ring ring-three" /><span className="network-beam beam-one" /><span className="network-beam beam-two" /><span className="network-beam beam-three" /><span className="network-point point-one"><i /></span><span className="network-point point-two"><i /></span><span className="network-point point-three"><i /></span><span className="network-point point-four"><i /></span><span className="network-center"><b>IN</b><small>EDGE CORE</small></span><div className="network-readout readout-one"><span>LATENCY</span><b>42ms</b></div><div className="network-readout readout-two"><span>NODES</span><b>128</b></div></div>;
}

function DataBoard() {
  return <div className="data-board"><div className="board-head"><span>LIVE EDGE TELEMETRY</span><b><i /> STREAMING</b></div><div className="board-grid"><div className="board-axis"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div className="bars">{[72, 46, 84, 58, 91, 63, 78, 52, 88, 69, 95, 76].map((height, index) => <i key={index} style={{ "--bar-height": `${height}%`, "--bar-delay": `${index * 90}ms` } as React.CSSProperties} />)}</div><div className="board-scan" /></div><div className="board-foot"><span>SEA-01 <b>+18.4%</b></span><span>FRA-03 <b>+12.8%</b></span><span>SFO-02 <b>+24.1%</b></span></div></div>;
}

function FeatureGrid() {
  const items = [{ icon: <Globe2 />, code: "PRODUCT / CDN", title: "内容，就近抵达", text: "独立配置域名、源站、缓存和 TLS，让静态与动态内容从平台节点就近分发。", href: "/platform" }, { icon: <Network />, code: "PRODUCT / FRP", title: "服务，安全穿透", text: "独立创建内网隧道，用自研客户端把本地面板、API 或开发环境发布到公网。", href: "/tunnel" }, { icon: <Server />, code: "PLATFORM / NODES", title: "节点，由平台提供", text: "CDN 与 FRP 业务彼此隔离，共同使用 infNet 运营的边缘节点资源。", href: "https://monitor.infvar.com" }, { icon: <Radar />, code: "OBSERVE / 24×7", title: "状态，实时可见", text: "节点健康、CDN 命中、隧道连接和套餐用量，在一个控制平面分别呈现。", href: "https://monitor.infvar.com" }];
  return <div className="feature-grid marketing-feature-grid">{items.map((item, index) => <article className="marketing-feature" key={item.code}><div className="marketing-feature-top"><span className="feature-icon">{item.icon}</span><span>0{index + 1}</span></div><span className="marketing-code">{item.code}</span><h3>{item.title}</h3><p>{item.text}</p><a href={item.href}>探索模块 <ChevronRight size={14} /></a></article>)}</div>;
}

function ProductTracks() {
  return <section className="marketing-section split-section product-tracks"><div className="split-copy"><SignalTag>TWO PRODUCTS / ONE PLATFORM FLEET</SignalTag><h2>两条产品线，<br /><em>各自独立运行。</em></h2><p>CDN 面向公网内容分发：接入域名、设置源站、缓存并保护回源。FRP 面向私有服务发布：运行自研客户端、创建隧道、转发端口。它们不互相依赖，只共享 infNet 运营的边缘节点资源。</p><div className="track-points"><span><Globe2 size={16} /><b>CDN</b> 内容分发 / 缓存 / TLS</span><span><Network size={16} /><b>FRP</b> 内网穿透 / 隧道 / 端口</span></div></div><div className="track-diagram"><div className="track-node"><Server size={18} /><span>INFNET EDGE FLEET</span><b>平台边缘节点</b></div><div className="track-branch branch-cdn"><Globe2 size={17} /><span>CDN PIPELINE</span><b>用户请求 → 缓存 → 源站</b></div><div className="track-branch branch-frp"><Network size={17} /><span>FRP PIPELINE</span><b>本地服务 → 隧道 → 公网</b></div></div></section>;
}

function CTA({ title = "准备好把网络变成优势了吗？", text = "从一个套餐开始，几分钟后让你的服务出现在更近的地方。" }: { title?: string; text?: string }) { return <section className="marketing-cta"><div><SignalTag>READY WHEN YOU ARE</SignalTag><h2>{title}</h2><p>{text}</p></div><div className="marketing-cta-actions"><a className="button button-dark" href="/login">立即开始 <ArrowRight size={16} /></a><a className="marketing-text-link" href="/docs">阅读开发者文档 <ChevronRight size={15} /></a></div></section>; }

export default function MarketingSite({ page }: { page: MarketingPage }) { return <PageFrame page={page}>{page === "platform" && <PlatformPage />}{page === "platform" && <ProductTracks />}{page === "tunnel" && <TunnelPage />}{page === "network" && <NetworkPage />}{page === "pricing" && <PricingPage />}{page === "docs" && <DeveloperPage />}{(page === "platform" || page === "tunnel" || page === "pricing") && <MarketingLongform page={page} />}</PageFrame>; }

function MarketingLongform({ page }: { page: "platform" | "tunnel" | "pricing" }) {
  if (page === "platform") return <>
    <section className="long-section long-dark"><div className="long-kicker"><SignalTag>CDN / REQUEST PATH</SignalTag><span>01 — DELIVERY LOGIC</span></div><div className="long-heading"><h2>每一次请求，<br /><em>都走清晰的路径。</em></h2><p>边缘加速不是一个抽象的开关。它由域名接入、缓存判断、边缘响应和源站回源组成，每个环节都可以在控制台里看到结果。</p></div><div className="flow-grid"><article><b>01</b><Globe2 size={20} /><h3>用户请求</h3><p>用户访问你的业务域名，DNS 和 TLS 在平台边缘入口完成接入。</p></article><article><b>02</b><Radar size={20} /><h3>边缘判断</h3><p>节点根据缓存规则、请求类型和资源状态决定是否直接响应。</p></article><article><b>03</b><Server size={20} /><h3>回源保护</h3><p>只有需要更新的内容才回到源站，减少峰值压力并保持内容一致。</p></article></div></section>
    <section className="long-section"><div className="long-heading"><SignalTag>CDN / CONTROL SURFACE</SignalTag><h2>把复杂选项，<br /><em>变成几个明确动作。</em></h2><p>你不需要理解一整套网络设备，只需要配置对业务有意义的设置。</p></div><div className="control-grid"><article><Globe2 size={19} /><h3>域名与证书</h3><p>绑定业务域名，统一处理 HTTPS、证书状态与访问入口。</p><span>DNS / TLS / HOSTNAME</span></article><article><Zap size={19} /><h3>缓存策略</h3><p>按路径、文件类型和缓存时间组织规则，适配官网、下载站和 API。</p><span>CACHE / TTL / PURGE</span></article><article><ShieldCheck size={19} /><h3>源站保护</h3><p>隐藏源站细节，把回源流量收敛到可观测、可控制的边缘链路。</p><span>ORIGIN / ACCESS / HEALTH</span></article><article><Radar size={19} /><h3>命中与流量</h3><p>观察请求量、命中率、回源量和区域响应，让优化有数据依据。</p><span>HITS / TRAFFIC / LATENCY</span></article></div></section>
    <section className="long-section long-panel"><div className="long-heading"><SignalTag>CDN / USE CASES</SignalTag><h2>为真实业务，<br /><em>准备好不同的加速方式。</em></h2></div><div className="case-grid"><article><span>PRODUCT WEBSITE</span><h3>官网与营销页面</h3><p>让图片、脚本和页面资源在用户更近的节点响应，减少首屏等待。</p></article><article><span>DOWNLOAD CENTER</span><h3>安装包与文件分发</h3><p>大文件由边缘节点承接，源站专注版本管理与内容发布。</p></article><article><span>API / APP</span><h3>接口与动态业务</h3><p>区分可缓存与不可缓存请求，把访问链路和回源行为分开观察。</p></article></div></section>
    <section className="long-section long-dark final-detail"><div><SignalTag>EDGE ACCELERATION / READY</SignalTag><h2>让内容先到达，<br /><em>再谈增长。</em></h2><p>平台节点、线路和运行状态由 infNet 负责，你只需要专注域名、源站和内容本身。</p></div><a className="button button-dark" href="/login">配置 CDN <ArrowRight size={16} /></a></section>
  </>;
  if (page === "tunnel") return <>
    <section className="long-section long-dark"><div className="long-kicker"><SignalTag>FRP / CONNECTION MODEL</SignalTag><span>01 — PRIVATE TO PUBLIC</span></div><div className="long-heading"><h2>不改变网络结构，<br /><em>给服务增加入口。</em></h2><p>你的应用继续运行在原来的内网设备上。infNet 自研客户端建立加密连接，平台节点负责公网侧的接入与转发。</p></div><div className="flow-grid tunnel-flow"><article><b>LOCAL</b><Terminal size={20} /><h3>本地服务</h3><p>面板、API、开发环境或设备服务保持在内网。</p></article><article><b>CLIENT</b><LockKeyhole size={20} /><h3>自研客户端</h3><p>使用平台签发的凭证建立并维持安全连接。</p></article><article><b>EDGE</b><Network size={20} /><h3>平台节点</h3><p>公网请求通过 infNet 节点转发到已授权服务。</p></article></div></section>
    <section className="long-section"><div className="long-heading"><SignalTag>FRP / SCENARIOS</SignalTag><h2>内网穿透，<br /><em>不只是开发调试。</em></h2><p>从临时协作到长期服务发布，按隧道用途分别管理。</p></div><div className="case-grid tunnel-cases"><article><span>TEAM / REVIEW</span><h3>预览环境</h3><p>把尚未上线的项目交给客户或同事体验，结束后关闭隧道即可。</p></article><article><span>REMOTE / OPS</span><h3>远程管理</h3><p>为内部面板和运维接口提供受控入口，降低暴露面。</p></article><article><span>DEVICE / API</span><h3>设备接口</h3><p>让内网设备、家庭服务或实验室 API 在需要时可以被访问。</p></article></div></section>
    <section className="long-section long-panel"><div className="long-heading"><SignalTag>FRP / SAFETY LAYER</SignalTag><h2>连接可见，<br /><em>权限可控。</em></h2></div><div className="control-grid"><article><LockKeyhole size={19} /><h3>身份校验</h3><p>每条隧道绑定账户和配置，不依赖公开的匿名端口。</p><span>IDENTITY / TOKEN</span></article><article><ShieldCheck size={19} /><h3>加密传输</h3><p>客户端与节点之间使用加密通道，降低传输过程中的风险。</p><span>TLS / ENCRYPTED</span></article><article><Radar size={19} /><h3>心跳监测</h3><p>连接状态、最后心跳和异常断开会在控制台中保持可见。</p><span>HEARTBEAT / STATUS</span></article><article><Network size={19} /><h3>配置隔离</h3><p>CDN 路由与 FRP 隧道分别管理，互不影响业务配置。</p><span>SEPARATE / CONTROLLED</span></article></div></section>
    <section className="long-section final-detail"><div><SignalTag>PRIVATE CONNECTIVITY / READY</SignalTag><h2>你的内网，<br /><em>可以有选择地被看见。</em></h2><p>选择需要发布的服务，创建隧道并运行 infNet 客户端，其余连接工作由平台节点完成。</p></div><a className="button button-dark" href="/login">创建 FRP 隧道 <ArrowRight size={16} /></a></section>
  </>;
  return <>
    <section className="long-section long-dark"><div className="long-kicker"><SignalTag>PRICING / RESOURCE MODEL</SignalTag><span>01 — PAY FOR USAGE</span></div><div className="long-heading"><h2>买你需要的，<br /><em>保持清楚可控。</em></h2><p>套餐同时覆盖 CDN 流量和 FRP 隧道资源，具体能力分别展示，避免把两个独立产品混成一笔模糊费用。</p></div><div className="price-resource-grid"><article><Globe2 size={20} /><span>CDN RESOURCE</span><b>分发流量</b><p>用于页面、文件和可缓存内容的边缘分发。</p></article><article><Network size={20} /><span>FRP RESOURCE</span><b>隧道数量</b><p>用于本地服务发布、端口转发和连接管理。</p></article><article><Radar size={20} /><span>SHARED PLATFORM</span><b>控制台能力</b><p>订单、用量、状态和配置统一在一个账户里。</p></article></div></section>
    <section className="long-section"><div className="long-heading"><SignalTag>PRICING / COMPARISON</SignalTag><h2>不同阶段，<br /><em>对应不同资源。</em></h2></div><div className="comparison-table"><div><span>适合场景</span><b>Starter</b><b>Growth</b><b>Scale</b></div><div><span>FRP 隧道</span><strong>3 条</strong><strong>15 条</strong><strong>不限</strong></div><div><span>月流量</span><strong>100 GB</strong><strong>1 TB</strong><strong>5 TB</strong></div><div><span>适合对象</span><strong>个人项目</strong><strong>成长团队</strong><strong>高流量业务</strong></div></div></section>
    <section className="long-section long-panel"><div className="long-heading"><SignalTag>PRICING / INCLUDED</SignalTag><h2>每个套餐，<br /><em>都从可用开始。</em></h2><p>无需额外采购基础控制面能力，创建账户后即可管理服务、订单和用量。</p></div><div className="control-grid"><article><Check size={19} /><h3>控制台与 API</h3><p>服务配置、订单状态和用量数据保持统一入口。</p><span>CONTROL PLANE</span></article><article><Check size={19} /><h3>平台节点接入</h3><p>使用 infNet 提供的节点和线路，不需要自行部署中转基础设施。</p><span>PLATFORM EDGE</span></article><article><Check size={19} /><h3>状态与用量</h3><p>CDN 和 FRP 的关键资源分别展示，账单更容易理解。</p><span>USAGE / BILLING</span></article><article><Check size={19} /><h3>随时升级</h3><p>业务增长时再切换套餐，配置和账户数据保持不变。</p><span>FLEXIBLE SCALE</span></article></div></section>
    <section className="long-section final-detail"><div><SignalTag>PRICING / START SMALL</SignalTag><h2>先把第一项服务，<br /><em>稳定地跑起来。</em></h2><p>从适合当前业务的套餐开始，后续根据真实流量和隧道数量升级。</p></div><a className="button button-dark" href="/login">选择套餐 <ArrowRight size={16} /></a></section>
  </>;
}

function TunnelPage() {
  return <main className="marketing-page"><section className="marketing-hero tunnel-hero"><div className="marketing-hero-copy"><SignalTag>PRIVATE CONNECTIVITY / FRP</SignalTag><h1>把内网服务，<br /><em>安全带到公网。</em></h1><p>内网穿透是独立的产品能力。运行 infNet 自研客户端，创建一条受控隧道，把本地 API、面板、开发环境或设备服务发布出去。</p><div className="marketing-hero-actions"><a className="button button-dark" href="/login">创建隧道 <ArrowRight size={16} /></a><a className="marketing-text-link" href="/docs">查看接入文档 <ChevronRight size={15} /></a></div></div><div className="tunnel-visual"><div className="tunnel-device"><Terminal size={18} /><span>LOCAL SERVICE</span><b>127.0.0.1:8080</b></div><div className="tunnel-line"><i /><i /><i /><i /></div><div className="tunnel-node"><Server size={18} /><span>INFNET EDGE</span><b>PUBLIC RELAY</b></div><div className="tunnel-readout"><span>ENCRYPTED TUNNEL</span><strong>CONNECTED</strong><small>TLS 1.3 / 24 ms</small></div></div></section><section className="marketing-section tunnel-details"><div className="marketing-section-intro"><SignalTag>FRP / YOUR SERVICE</SignalTag><h2>本地服务的<br /><em>公网入口。</em></h2><p>你不需要暴露源站 IP，也不需要自己维护公网中转服务器。平台节点负责转发，你只管理自己的服务和隧道策略。</p></div><div className="tunnel-capabilities"><article><Network size={19} /><h3>自研客户端</h3><p>专用客户端负责身份交换、心跳和隧道连接，不直接使用开源 FRP 客户端。</p></article><article><LockKeyhole size={19} /><h3>短期凭证</h3><p>客户端按平台签发的配置建立连接，隧道状态、端口和操作记录可追踪。</p></article><article><Zap size={19} /><h3>快速上线</h3><p>配置隧道后复制命令，在你的设备上运行即可开始转发。</p></article></div></section><CTA title="让内网服务，随时可访问。" text="选择 FRP 资源，获取你的客户端配置和隧道凭证。" /></main>;
}

function PlatformPage() {
  return <main className="marketing-page"><section className="marketing-hero platform-hero"><div className="marketing-hero-copy"><SignalTag>THE INFRASTRUCTURE LAYER</SignalTag><h1>基础设施不该<br /><em>挡在产品之前。</em></h1><p>infNet 把 CDN、私有隧道、边缘节点和可观测性收进一套清晰的网络操作系统。</p><div className="marketing-hero-actions"><a className="button button-dark" href="/login">进入控制台 <ArrowRight size={16} /></a><a className="marketing-text-link" href="/network">查看网络状态 <ChevronRight size={15} /></a></div></div><div className="marketing-hero-visual"><AnimatedNetwork large /></div></section><section className="marketing-band"><div className="metric-line"><span>ONE CONTROL PLANE</span><b>1</b><span>EDGE NODES</span><b>128+</b><span>AVERAGE RESPONSE</span><b>42ms</b><span>UPTIME TARGET</span><b>99.99%</b></div></section><section className="marketing-section"><div className="marketing-section-intro"><SignalTag>FOUR SYSTEMS / ONE SURFACE</SignalTag><h2>每一层，都为<br /><em>上线而设计。</em></h2><p>不用在不同供应商之间拼接工具。平台从接入、分发到计量，保持同一套状态模型。</p></div><FeatureGrid /></section><section className="marketing-section split-section"><div className="code-panel"><div className="code-panel-head"><span>INFNET / AGENT</span><span>READY TO DEPLOY</span></div><pre>{"$ curl -fsSL https://infvar.com/install | sh\n$ infnet-agent bootstrap\n\n[ ok ] secure identity created\n[ ok ] edge capabilities detected\n[ ok ] desired state synchronized"}</pre><div className="code-cursor" /></div><div className="split-copy"><SignalTag>FROM SERVER TO NETWORK</SignalTag><h2>一条命令，<br /><em>接入你的边缘。</em></h2><p>服务器仍然属于你。edge-agent 只执行平台签发的配置，不接管你的系统，不隐藏任何基础设施。</p><a className="marketing-text-link" href="/docs">查看接入流程 <ChevronRight size={15} /></a></div></section><CTA /></main>;
}

function NetworkPage() {
  return <main className="marketing-page"><section className="marketing-hero network-hero"><div className="marketing-hero-copy"><SignalTag>GLOBAL EDGE FABRIC</SignalTag><h1>你的服务，<br /><em>离用户更近。</em></h1><p>从一台服务器开始，逐步构建属于你的边缘网络。节点上线、健康、配置和流量，在这里持续流动。</p><div className="network-status-line"><i />所有系统运行正常 <span>·</span> 128 个节点已连接</div></div><div className="marketing-hero-visual"><AnimatedNetwork large /></div></section><section className="marketing-section telemetry-section"><div className="telemetry-copy"><SignalTag>TELEMETRY / LIVE</SignalTag><h2>网络不是一张地图。<br /><em>它是一条实时信号。</em></h2><p>每一次心跳都转化为可操作的状态：节点是否在线、线路是否同步、流量是否接近额度。</p><div className="telemetry-list"><span><ShieldCheck size={15} /> TLS 1.3 节点身份</span><span><Zap size={15} /> 期望状态自动同步</span><span><LockKeyhole size={15} /> 短期凭证与审计记录</span></div></div><DataBoard /></section><section className="marketing-section region-section"><div className="marketing-section-intro"><SignalTag>DEPLOY ANYWHERE</SignalTag><h2>从一个区域，<br /><em>扩展到全世界。</em></h2></div><div className="region-grid"><div className="region-card active"><span>AP-SOUTHEAST-1</span><b>Singapore / SEA</b><strong>42ms</strong><i>ONLINE</i></div><div className="region-card"><span>EU-CENTRAL-1</span><b>Frankfurt / EU</b><strong>128ms</strong><i>READY</i></div><div className="region-card"><span>US-WEST-2</span><b>Oregon / US</b><strong>164ms</strong><i>READY</i></div></div></section><CTA title="让下一次请求，走更短的路。" text="连接你的第一台节点，开始观察真实网络数据。" /></main>;
}

function PricingPage() {
  const plans = [{ name: "Starter", price: "19", detail: "个人项目与小型服务", list: ["3 条 FRP 隧道", "100 GB 月流量", "CDN 缓存与 TLS 1.3"] }, { name: "Growth", price: "69", detail: "成长中的团队与产品", list: ["15 条 FRP 隧道", "1 TB 月流量", "多节点自动同步", "优先技术支持"] }, { name: "Scale", price: "199", detail: "高流量业务与多节点", list: ["不限 FRP 隧道", "5 TB 月流量", "自定义边缘网络", "高级运营支持"] }];
  return <main className="marketing-page"><section className="marketing-hero pricing-hero"><div className="marketing-hero-copy"><SignalTag>SIMPLE / TRANSPARENT / READY</SignalTag><h1>按你正在构建的<br /><em>未来来选择。</em></h1><p>不锁长期合约，不把基础设施拆成难以理解的费用。先小规模开始，随着服务一起增长。</p></div><div className="pricing-orbit"><div className="orbit-label label-top">CDN</div><div className="orbit-label label-right">FRP</div><div className="orbit-label label-bottom">EDGE</div><div className="orbit-core">¥<b>19</b><small>起 / 月</small></div></div></section><section className="marketing-section pricing-page-section"><div className="pricing-page-grid">{plans.map((plan, index) => <article className={index === 1 ? "marketing-price-card featured" : "marketing-price-card"} key={plan.name}>{index === 1 && <span className="price-ribbon">MOST POPULAR</span>}<span className="marketing-code">{index === 0 ? "01 / START" : index === 1 ? "02 / GROW" : "03 / SCALE"}</span><h2>{plan.name}</h2><p>{plan.detail}</p><div className="marketing-price"><b>¥{plan.price}</b><span>/ 月</span></div><ul>{plan.list.map((line) => <li key={line}><Check size={15} />{line}</li>)}</ul><a className="button button-dark" href="/login">选择 {plan.name} <ArrowRight size={15} /></a></article>)}</div></section><section className="marketing-section price-note"><SignalTag>EVERY PLAN INCLUDES</SignalTag><div className="include-grid"><span><Check size={15} />控制台与 API</span><span><Check size={15} />自动初始化数据库</span><span><Check size={15} />边缘节点同步</span><span><Check size={15} />按量用量统计</span></div></section><CTA title="从今天开始，让网络为你工作。" /></main>;
}

function DeveloperPage() {
  return <main className="marketing-page"><section className="marketing-hero docs-hero"><div className="marketing-hero-copy"><SignalTag>BUILD WITH INFNET</SignalTag><h1>给开发者的<br /><em>清晰路径。</em></h1><p>从创建服务到查看状态，所有关键步骤都在控制台完成。平台节点、线路和公网接入由 infNet 负责。</p><div className="marketing-hero-actions"><a className="button button-dark" href="/login">打开控制台 <ArrowRight size={16} /></a><a className="marketing-text-link" href="/tunnel">了解内网穿透 <ChevronRight size={15} /></a></div></div><div className="terminal-visual"><div className="terminal-top"><span /><span /><span /><b>infnet / service-config</b></div><pre><span className="code-muted">01</span> create service<br /><span className="code-muted">02</span> choose CDN or FRP<br /><span className="code-ok">✓ platform resources ready</span><br /><span className="code-ok">✓ service status visible</span></pre></div></section><section className="long-section long-dark"><div className="long-heading"><SignalTag>DEVELOPER / WORKFLOW</SignalTag><h2>从选择服务开始，<br /><em>每一步都有反馈。</em></h2><p>你可以分别配置 CDN 加速和 FRP 内网穿透，它们共享账户和平台节点，但配置、状态与用量互相隔离。</p></div><div className="flow-grid"><article><b>01</b><Globe2 size={20} /><h3>配置边缘加速</h3><p>填写域名、源站和缓存规则，发布 CDN 路由。</p></article><article><b>02</b><Network size={20} /><h3>创建内网隧道</h3><p>填写本地服务和转发策略，获得专用客户端配置。</p></article><article><b>03</b><Radar size={20} /><h3>持续查看状态</h3><p>在控制台或节点监控中查看服务、线路和用量。</p></article></div></section><section className="long-section"><div className="long-heading"><SignalTag>DEVELOPER / PRINCIPLES</SignalTag><h2>少一点基础设施，<br /><em>多一点产品确定性。</em></h2></div><div className="control-grid"><article><ShieldCheck size={19} /><h3>默认安全</h3><p>服务以可控身份和加密连接为基础，不要求你暴露不必要的网络细节。</p><span>SECURITY FIRST</span></article><article><Globe2 size={19} /><h3>配置清楚</h3><p>CDN 与 FRP 分开管理，页面只呈现当前服务真正需要的选项。</p><span>SEPARATE PRODUCTS</span></article><article><Radar size={19} /><h3>状态可见</h3><p>从节点健康到业务用量，重要信号不会藏在日志深处。</p><span>OBSERVABLE</span></article><article><Zap size={19} /><h3>按需增长</h3><p>先从一个服务开始，根据真实使用情况升级资源和套餐。</p><span>START SMALL</span></article></div></section><CTA title="准备好开始配置了吗？" text="登录平台，选择边缘加速或内网穿透服务。" /></main>;
}

function DocsPage() {
  return <main className="marketing-page"><section className="marketing-hero docs-hero"><div className="marketing-hero-copy"><SignalTag>BUILD WITH INFNET</SignalTag><h1>给开发者的<br /><em>清晰路径。</em></h1><p>从安装 agent 到发布第一条隧道，所有关键步骤都保持短、直接、可验证。</p><div className="marketing-hero-actions"><a className="button button-dark" href="#quickstart">快速开始 <ArrowRight size={16} /></a><a className="marketing-text-link" href="/login">打开控制台 <ChevronRight size={15} /></a></div></div><div className="terminal-visual"><div className="terminal-top"><span /><span /><span /><b>infnet / quickstart</b></div><pre><span className="code-muted">$</span> curl -fsSL https://infvar.com/install | sh<br /><span className="code-muted">$</span> infnet-agent register --bootstrap<br /><span className="code-ok">✓ node connected / cn-shanghai</span><br /><span className="code-ok">✓ desired state applied</span></pre></div></section><section className="marketing-section docs-section" id="quickstart"><div className="docs-sidebar"><span className="marketing-code">DOCS / 00</span><b>快速开始</b><span>节点接入</span><span>FRP 客户端</span><span>CDN 路由</span><span>API 参考</span></div><div className="docs-content"><SignalTag>QUICKSTART</SignalTag><h2>三步连接你的第一台节点。</h2><div className="doc-step"><b>01</b><div><h3>创建节点身份</h3><p>在管理员后台创建节点，复制一次性 bootstrap token。</p></div></div><div className="doc-step"><b>02</b><div><h3>运行 edge-agent</h3><p>在你的服务器上执行安装命令，agent 会自动交换长期身份并开始心跳。</p></div></div><div className="doc-step"><b>03</b><div><h3>发布服务</h3><p>在控制台选择 CDN 路由或 FRP 隧道，节点会自动领取配置。</p></div></div></div></section><CTA title="准备连接你的第一台节点？" text="登录控制台，获取你的 bootstrap token 和部署命令。" /></main>;
}
